---
title: "US Economic Data"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center",
                      dpi = 144)
remove(list = ls(all.names = TRUE))
detachAllPackages <- function() {
  basic.packages.blank <-  c("stats","graphics","grDevices","utils","datasets","methods","base")
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1,TRUE,FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0)  for (package in package.list) {
    detach(package, character.only = TRUE)}}
detachAllPackages()
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

p_load(flexdashboard,readxl,tidyverse,highcharter,readr,timetk,quantmod,caTools,blscrapeR,rUnemploymentData)
```

```{r,  Function to Load Stock Market Data & LM}
SymbolsGraph <- function(symb,startDate) {
  temp <- getSymbols(symb,auto.assign = F,from = startDate)
  
  temp <- data.frame(temp,Date = index(temp)) %>%
    select(Date,"Close" = contains('Close'))
  lm <- lm(Close ~ Date,temp)
  results <- summary(lm)
  temp <- temp %>%
    mutate(fitted = round(lm$fitted.values,2),
           Close = round(Close,2))
  
  tempXTS <- xts(temp[,-1],order.by = temp$Date)
  
  highchart(type = "stock") %>%
    hc_add_series(tempXTS$Close,type = 'line') %>%
    hc_add_series(tempXTS$fitted,type = 'line') %>%
    hc_title(text = paste(symb,'Linear Regression',sep = ' '))
}
```

```{r, Unemployment Data}
## Data From https://data.oecd.org/
unemp <- read.csv('unemployment.csv') %>%
  filter(`ï..LOCATION` == 'USA' & FREQUENCY == 'M' & SUBJECT == 'TOT') %>%
  separate(TIME,into = c('Year','Month'),sep = '-') %>%
  mutate(Date = as.Date(paste(Year,Month,'01',sep = '-'),'%Y-%m-%d')) %>%
  filter(Date > as.Date('2004-12-01'))
unempYEAR <- read.csv('unemployment.csv') %>%
  filter(`ï..LOCATION` == 'USA' & FREQUENCY == 'Y' & SUBJECT == 'TOT')
unempReduction <- unemp %>%
  filter(Date %in% c(as.Date('2009-07-01'),as.Date('2017-01-01'),as.Date('2020-02-01'))) %>%
  mutate(reduction = abs(Value - lag(Value)))
```

```{r, Record Highs}
records <- getSymbols('^DJI',auto.assign = F,from = '2001-01-20')
records <- data.frame(records,Date = index(records)) %>%
  select(Date,"High" = contains('High')) %>%
  mutate(President = case_when(Date < as.Date('2009-01-20') ~ 'George W. Bush',
                               Date < as.Date('2017-01-20') ~ 'Barack Obama',
                               TRUE ~ 'Donald Trump'))
high <- records$High[1]
for (i in 1:nrow(records)) {
  if (records$High[i] > high) {
    records$recordHigh[i] = 1
    high <- records$High[i]
  }
  else {
    records$recordHigh[i] = 0
  }
}

recordHighs <- records %>%
  group_by(President) %>%
  summarise(recordHighs = sum(recordHigh),
            days = n())


```

```{r, Avg Daily Change}
daily <- getSymbols('^GSPC',auto.assign = F,from = '2001-01-20')
daily <- data.frame(daily,'Date' = index(daily)) %>%
  select(Date,'Open' = contains('Open'),'Close' = contains('Close')) %>%
  mutate(DailyChange = Close - Open,
         President = case_when(Date < as.Date('2009-01-20') ~ 'George W. Bush',
                               Date < as.Date('2017-01-20') ~ 'Barack Obama',
                               TRUE ~ 'Donald Trump')) %>%
  group_by(President) %>%
  summarise(AvgDailyChange = mean(DailyChange,na.rm = T))

```

# Unemployment/Jobs Data and Trends

##

###

```{r}
valueBox(value = paste(unempReduction$reduction[2],'% Unemployment Reduction',sep = ''),
         caption = 'July 2009 to Jan 2017 (Post Great Recession)')
```

###

```{r}
valueBox(value = paste(unempReduction$reduction[3],'% Unemployment Reduction',sep = ''),
         caption = 'Jan 2017 to February 2020')
```

##

###

```{r}
hchart(unemp,'line',hcaes(x = Date,y = Value)) %>%
  hc_add_theme(hc_theme_smpl()) %>%
  hc_yAxis(min = 0,title = list(text = 'Unemployment Percent (%)')) %>%
  hc_xAxis(plotBands = list(list(from = datetime_to_timestamp(as.Date('2007-12-01')),to = datetime_to_timestamp(as.Date('2009-06-01')), color = '#F0B58A',
                                 label = list(text = 'Great Recession')),
                            list(from = datetime_to_timestamp(as.Date('2020-03-01')),to = JS('Infinity'),color = '#F0B58A',
                                 label = list(text = 'COVID-19'))))
```

# Stock Market Data and Trends

## {.tabset .tabset-fade}

### S&P 500

```{r}
SymbolsGraph('^GSPC','2009-01-20')
```

### Dow Jones

```{r}
SymbolsGraph('^DJI','2009-01-20')
```

### Nasdaq

```{r}
SymbolsGraph('^IXIC','2009-01-20')
```
